### ISSUE TITLE
Computed property accesses incorrectly transformed when using the Typescript parser

### ISSUE THREAD

**Issue by AndersDJohnson** [cdlewis/idx-to-optional-chaining#12]
It seems this replaces `idx(o, _ => _.a[0])` with `o?.a?.0` whereas it should be `o?.a?.[0]`.

**Comment by cdlewis** [comment]
This definitely used to be a problem but it should've been fixed in December last year. I just manually verified on master that the output is `o?.a?.[0]`.

It's possible you're running an old version of the transform? I never bumped the version in package.json.

**Comment by AndersDJohnson** [comment]
I thought I cloned the latest from here on GitHub just a few weeks back but 🤷‍♂

**Comment by cdlewis** [comment]
The specific example you pasted worked for me, perhaps there's some more nuance in the code you're transforming that's causing the issue?

**Comment by sibelius** [comment]
@AndersDJohnson can you add a failing test?

**Comment by sibelius** [comment]
it is breaking for us as well

here is a simple failing test

input:

`idx(items, _ => _[0].totalCount) || 0;`

output:

`items?.0?.totalCount || 0;`

**Comment by cdlewis** [comment]
Interesting, I added a test fixture that tries to capture this situation and it gets transformed correctly. Unless there's some surrounding context or idiosyncrasy that I'm missing.

https://github.com/cdlewis/idx-to-optional-chaining/blob/master/__testfixtures__/common-variations.input.js#L23
https://github.com/cdlewis/idx-to-optional-chaining/blob/master/__testfixtures__/common-variations.output.js#L21

**Comment by cdlewis** [comment]
I also cloned the project from scratch and ran it on a test file containing your input :/

**Comment by cdlewis** [comment]
As a sanity check, do you mind pasting the contents of `idx-to-optional-chaining/index.js` from the `jscodeshift -t idx-to-optional-chaining/index.js ..` statement?

**Comment by sibelius** [comment]
```jsx
function shouldTransformNode(currentNode, root) {
  let current = currentNode;
  while (current !== root){
    const parentComputed = current && current.parent && current.parent.value && current.parent.value.computed;
    const parentObject = current && current.parent && current.parent.value && current.parent.value.object;

    if (parentComputed && parentObject !== current.value) {
    	return false;
    }
    
    current = current.parent;
  }
  
  return true;
}

function transformer(file, api) {
  const j = api.jscodeshift;
  const root = j(file.source);
  const getFirstNode = () => root.find(j.Program).get("body", 0).node;

  // Save the comments attached to the first node
  const firstNode = getFirstNode();
  const { comments } = firstNode;

  root
    .find(j.ImportDeclaration)
    .filter(path => path.node.source.value === "idx")
    .forEach(path => j(path).remove());

  root.find(j.CallExpression).forEach(path => {
    if (path.value.callee.name !== "idx") {
      return;
    }

    const rootObject = path.value.arguments[0];

    // Narrow search to within the arrow function to avoid mutating first argument to idx
    j(path)
      .find(j.ArrowFunctionExpression)
      .find(j.MemberExpression)
      .forEach(exp => {
        // Don't transform member expressions within a computed property access
        // e.g. ignore the 'window.location' part of idx(x, _ => _[`${window.location}`])
        if (!shouldTransformNode(exp, path, ['MemberExpression', 'ArrowFunctionExpression', 'OptionalMemberExpression'])) {
          return;
        }

        // For the 'root' element add the object being accessed
        // e.g. idx(x, _.a) to idx(x, x?.a)
        if (exp.value.object.name) {
          return j(exp).replaceWith(
          	j.optionalMemberExpression(
              rootObject,
              exp.value.property,
            )
          );
        }

        // Convert every other MemberExpression to an OptionalMemberExpression
        if (exp.value.object && exp.value.property) {
          j(exp).replaceWith(
            j.optionalMemberExpression(
              exp.value.object,
              exp.value.property,
              exp.value.computed
            )
          );
        }
      });

    // Replace the idx call with its second argument
    j(path).replaceWith(path.value.arguments[1].body);
  });

  // If the first node has been modified or deleted, reattach the comments
  const firstNode2 = getFirstNode();
  if (firstNode2 !== firstNode) {
    firstNode2.comments = comments;
  }

  return root.toSource();
};

module.exports = transformer;
module.exports.parser = 'tsx';
```

My only change is this:

```jsx
module.exports.parser = 'tsx';
```

to make it work with typescript, I've also modify the jscodeshift to latest version 0.7.x

**Comment by sibelius** [comment]
failing test here https://github.com/cdlewis/idx-to-optional-chaining/pull/13

**Comment by cdlewis** [comment]
Thanks, I think we got to the bottom of this, it's the typescript parser :)

I'm investigating how to fix this.

**Comment by cdlewis** [comment]
I've landed something that seems to fix this: https://github.com/cdlewis/idx-to-optional-chaining/commit/53680439b9a7e65061315c129dac750758890cae

It seemed a little too simple, but all the tests are passing :/

Let me know if that works for you.

**Comment by sibelius** [comment]
we can close this
