### ISSUE TITLE
edge case of idx with single value access

### ISSUE THREAD

**Issue by sibelius** [cdlewis/idx-to-optional-chaining#14]
input:

```jsx
idx(row[key], _ => _)
```

output

```jsx
_
```

it should be `row[key]`

**Comment by cdlewis** [comment]
I think https://github.com/cdlewis/idx-to-optional-chaining/commit/4d340471653e115fe9ccc2d479fcd97cc3f17ad4 should resolve this

**Comment by sibelius** [comment]
you rock, tks
