### ISSUE TITLE
wrong transform with `!` typescript operation

### ISSUE THREAD

**Issue by sibelius** [cdlewis/idx-to-optional-chaining#15]
input
```jsx
idx(value, _ => _!.currentValue) || 0;
```

output
```jsx
_!?.currentValue || 0;
```

expected

```jsx
value.currentValue || 0
```

**Comment by cdlewis** [comment]
So we should always remove the non-null assertion operator?

**Comment by sibelius** [comment]
yes

**Comment by cdlewis** [comment]
I've pushed a new commit that should address this https://github.com/cdlewis/idx-to-optional-chaining/commit/cae18f0ce21b279cf6a2cca85035d044e4f1c08c

**Comment by sibelius** [comment]
fixed
