### ISSUE TITLE
Does not support using anything other than `_` in callback

### ISSUE THREAD

**Issue by TJTorola** [cdlewis/idx-to-optional-chaining#4]
When running this on our codebase, we first needed to change all calls to idx to use `_` as the callback var name. So for example:

`idx(foo, f => f.bar.baz)` would incorrectly change to `foo?.f?.bar?.baz`
whereas:
`idx(foo, _ => _.bar.baz)` would correctly change to `foo?.bar?.baz`

**Comment by TJTorola** [comment]
Awesome! thanks.

**Comment by cdlewis** [comment]
Hopefully this won't create any weird edge cases 🤞

**Comment by TJTorola** [comment]
Thanks!, We still have a couple of other spots in our codebase that use idx, so I can run it on those and see if it checks out.
