### ISSUE TITLE
Incorrectly parses when brackets are used first

### ISSUE THREAD

**Issue by TJTorola** [cdlewis/idx-to-optional-chaining#5]
Failing example:
`idx(foo, _ => _[bar])` would parse as `foo?.bar`
Where we expected `foo?.[bar]`

**Comment by cdlewis** [comment]
Yeah I got a little lazy on this one. Feel free to open a PR.

**Comment by cdlewis** [comment]
I want to test more before merging but I *think* my PR should fix this issue
